---
title: Ntdb.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Nate Bailey
highlighter: rouge
category-list:
- Web
- Mobile
- Games
icon-list:
- desktop
- mobile
- gamepad
